<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>tactical-ddd-workshop-04-modulith</artifactId>

	<name>Tactical DDD Workshop - Moduliths</name>

	<parent>
		<groupId>de.odrotbohm.examples</groupId>
		<artifactId>tactical-ddd-workshop</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.modulith</groupId>
				<artifactId>spring-modulith-bom</artifactId>
				<version>${spring-modulith.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<!-- Spring Modulith -->

		<dependency>
			<groupId>org.springframework.modulith</groupId>
			<artifactId>spring-modulith-starter-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.modulith</groupId>
			<artifactId>spring-modulith-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Persistence -->

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-json</artifactId>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>

		<!-- jMolecules -->

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jmolecules.integrations</groupId>
			<artifactId>jmolecules-starter-ddd</artifactId>
		</dependency>


		<dependency>
			<groupId>org.jmolecules.integrations</groupId>
			<artifactId>jmolecules-jackson</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.jmolecules.integrations</groupId>
			<artifactId>jmolecules-jpa</artifactId>
			<scope>runtime</scope>
		</dependency>

<!--		<dependency>-->
<!--			<groupId>org.jmolecules.integrations</groupId>-->
<!--			<artifactId>jmolecules-bytebuddy-nodep</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>

			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.jmolecules</groupId>
			<artifactId>jmolecules-hexagonal-architecture</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jmolecules.integrations</groupId>
			<artifactId>jmolecules-archunit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>3.2.2</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>

<!--			<plugin>-->
<!--				<groupId>net.bytebuddy</groupId>-->
<!--				<artifactId>byte-buddy-maven-plugin</artifactId>-->
<!--				<version>${bytebuddy.version}</version>-->
<!--				<executions>-->
<!--					<execution>-->
<!--						<goals>-->
<!--							<goal>transform-extended</goal>-->
<!--						</goals>-->
<!--					</execution>-->
<!--				</executions>-->
<!--				<configuration>-->
<!--					<classPathDiscovery>true</classPathDiscovery>-->
<!--				</configuration>-->
<!--			</plugin>-->


<!--				Enable custom Javadoc Doclet to extract Javadoc into a JSON File-->
<!--				so that it can be included in generated documentation.-->

			<plugin>
				<groupId>com.societegenerale.commons</groupId>
				<artifactId>arch-unit-maven-plugin</artifactId>
				<version>4.0.2</version>
				<configuration>
					<properties>
						<archunit.propertyName>propertyValue</archunit.propertyName>
					</properties>
					<rules>
						<preConfiguredRules>
							<rule>com.societegenerale.commons.plugin.rules.NoStandardStreamRuleTest</rule>
<!--							<rule>com.societegenerale.commons.plugin.rules.NoJunitAssertRuleTest</rule>-->
							<rule>com.societegenerale.commons.plugin.rules.NoJodaTimeRuleTest</rule>
							<rule>com.societegenerale.commons.plugin.rules.NoJavaUtilDateRuleTest</rule>
							<rule>com.societegenerale.commons.plugin.rules.NoPowerMockRuleTest</rule>
							<rule>com.societegenerale.commons.plugin.rules.NoPrefixForInterfacesRuleTest</rule>
							<rule>com.societegenerale.commons.plugin.rules.NoPublicFieldRuleTest</rule>
<!--							<rule>com.societegenerale.commons.plugin.rules.HexagonalArchitectureTest</rule>-->


							<!--							<rule>com.societegenerale.commons.plugin.rules.DontReturnNullCollectionTest</rule>-->
<!--							<rule>com.societegenerale.commons.plugin.rules.ConstantsAndStaticNonFinalFieldsNamesRuleTest </rule>-->


							<!-- you may want to use one of the below rules, but not both at same time -->
							<rule>com.societegenerale.commons.plugin.rules.NoTestIgnoreRuleTest</rule>
<!--							<rule>com.societegenerale.commons.plugin.rules.NoTestIgnoreWithoutCommentRuleTest</rule>-->

							<rule>com.societegenerale.commons.plugin.rules.NoInjectedFieldTest</rule>
<!--							<rule>com.societegenerale.commons.plugin.rules.NoAutowiredFieldTest</rule>-->
						</preConfiguredRules>
					</rules>
				</configuration>
				<executions>
					<execution>
						<phase>test</phase>
						<goals>
							<goal>arch-test</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<!--
                             A version of the core jar is included by default, but don't hesitate
                             to upgrade to a later one if you need :
                             we will be able to add rules and behavior in arch-unit-build-plugin-core
                             without releasing a new version of arch-unit-maven-plugin
                         -->
						<groupId>com.societegenerale.commons</groupId>
						<artifactId>arch-unit-build-plugin-core</artifactId>
						<version>4.0.1</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>com.github.davidmoten</groupId>
				<artifactId>plantuml-maven-plugin</artifactId>
				<version>0.2.13</version>
				<executions>
					<execution>
						<id>generate-diagrams</id>
						<phase>install</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>

				<configuration>
					<sources>
						<directory>${project.basedir}/target/spring-modulith-docs</directory>
						<includes>
							<include>*.puml</include>
						</includes>
						<excludes>
							<exclude>**/ignore-me.puml</exclude>
						</excludes>
					</sources>
					<outputDirectory>${project.basedir}/src/main/asciidoc/images</outputDirectory>
					<formats>
						<format>png</format>
						<format>svg</format>
					</formats>
					<preserveDirectoryStructure>false</preserveDirectoryStructure>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok-maven-plugin</artifactId>
				<version>1.18.20.0</version>
				<dependencies>
					<dependency>
						<groupId>org.projectlombok</groupId>
						<artifactId>lombok</artifactId>
						<version>${lombok.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							 <goal>delombok</goal>
						</goals>
						<configuration>
							<addOutputDirectory>false</addOutputDirectory>
							<sourceDirectory>src/main/java</sourceDirectory>
							<outputDirectory>${project.build.directory}/delombok	</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

</project>
